---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: "{{ANSIBLE_SSH_USER}}"

  vars_files:
    - ./vars/base.yml

  tasks:

    - name: check if flutter is already downloaded
      stat: path=/usr/local/{{FLUTTER_VERSION}}.tar.xz
      register: flutter_file_exist
      tags:
        - install_flutter
        - flutter  

    - name: download flutter
      shell: sudo wget --directory-prefix=/usr/local  https://storage.googleapis.com/flutter_infra/releases/beta/linux/{{FLUTTER_VERSION}}.tar.xz
      when: flutter_file_exist.stat.exists == False
      tags:
        - install_flutter
        - flutter

    - name: untar flutter file
      command: sudo tar xf /usr/local/{{FLUTTER_VERSION}}.tar.xz chdir=/usr/local/
      tags:
        - install_flutter
        - flutter

    - name: flutter profileI
      lineinfile: line="\n#flutter"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root
      tags:
        - flutter

    - name: flutter profileII
      lineinfile: line="export PATH=$PATH:/usr/local/flutter/bin"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root
      tags:
        - flutter

    - name: flutter bashrcI
      lineinfile: line="\n#flutter"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - flutter

    - name: flutter bashrcII
      lineinfile: line="export PATH=$PATH:/usr/local/flutter/bin"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - flutter

    - name: source profile
      shell: source /etc/profile
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash
      tags:
        - flutter

    - name: source bashrc
      shell: source ~/.bashrc
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash
      tags:
        - flutter

    - name: give {{ansible_ssh_user}} perms on flutter dir
      shell: chown -R {{ansible_ssh_user}} /usr/local/flutter
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - flutter

        