---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: root

  vars_files:
    - ./vars/base.yml

  tasks:

    - name: download golang
      shell: sudo wget --directory-prefix=/usr/local {{GOLANG_DOWNLOAD_URL}}

    - name: untar golang file
      shell: sudo tar --directory=/usr/local -xzf go1.4.2.linux-amd64.tar.gz

    - name: golang profileI
      lineinfile: line="#golang"
                  backup=yes
                  dest=~/.profile

    - name: golang profileII
      lineinfile: line="export PATH=$PATH:/usr/local/go/bin"
                  backup=yes
                  dest=~/.profile

    - name: create golang code dir
      shell: mkdir -p $HOME/mystuff/gocode

    - name: export golang code dir
      lineinfile: line="export GOPATH=$HOME/mystuff/gocode"
                  backup=yes
                  dest=~/.profile

    - name: create golang code github dir
      shell: mkdir -p $HOME/mystuff/gocode/src/github.com/komuw

    - name: source profile
      shell: . ~/.profile
      ignore_errors: yes