---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: "{{ANSIBLE_SSH_USER}}"

  vars_files:
    - ./vars/base.yml

  tasks:

    - name: check if golang is already downloaded
      stat: path=/usr/local/{{GOLANG_VERSION}}.tar.gz
      register: golang_file_exist
      tags:
        - install_go
        - golang

    - name: download golang
      shell: sudo wget --directory-prefix=/usr/local https://storage.googleapis.com/golang/{{GOLANG_VERSION}}.tar.gz
      when: golang_file_exist.stat.exists == False
      tags:
        - install_go
        - golang

    - name: untar golang file
      command: sudo tar -xzf /usr/local/{{GOLANG_VERSION}}.tar.gz chdir=/usr/local/
      tags:
        - install_go
        - golang

    - name: golang profileI
      lineinfile: line="\n#golang"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root
      tags:
        - golang

    - name: golang profileII
      lineinfile: line="export PATH=$PATH:/usr/local/go/bin"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root
      tags:
        - golang

    - name: export golang code dir(well use the default one)
      lineinfile: line="export GOPATH=$HOME/go"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root

    - name: create golang code github dir
      shell: mkdir -p $HOME/go/src/github.com/komuw
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - golang

    - name: golang bashrcI
      lineinfile: line="\n#golang"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - golang

    - name: golang bashrcII
      lineinfile: line="export PATH=$PATH:/usr/local/go/bin"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - golang

    - name: export golang code dir in bashrc
      lineinfile: line="export GOPATH=$HOME/go"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      tags:
        - golang

    - name: add $GOPATH to $PATH
      lineinfile: line="export PATH=$HOME/go/bin:$PATH"
                  backup=yes
                  dest=/etc/profile
      sudo: yes
      sudo_user: root
      tags:
        - golang

    - name: source profile
      shell: source /etc/profile
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash
      tags:
        - golang

    - name: source bashrc
      shell: source ~/.bashrc
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash
      tags:
        - golang

    - name: go get some golang packages
      shell: export GOPATH="$HOME/go" && source /etc/profile && go get -u {{item}}
      with_items:
        - github.com/motemen/gore                 # golang repl
        - github.com/nsf/gocode                   # golang auto-completion
        - github.com/k0kubun/pp                   # pretty print
        - golang.org/x/tools/cmd/godoc            # docs
        - github.com/derekparker/delve/cmd/dlv    # debugger
        - github.com/rs/zerolog                   # zero allocation logger
        - github.com/pkg/errors                   # nice error handling
        - github.com/alecthomas/gometalinter      # linter of linters
        - github.com/d4l3k/go-pry                 # debugger/repl
        - github.com/sourcegraph/go-langserver    # vscode stuff
        - github.com/golang/dep/cmd/dep           # dependency mgmnt
        - github.com/google/gops                  # ps for golang apps
        - github.com/sanity-io/litter             # pretty print
        - github.com/rogpeppe/godef               # vscode stuff
        - github.com/golang/lint/golint           # vscode stuff
        - github.com/lukehoban/go-outline         # vscode stuff
        - sourcegraph.com/sqs/goreturns           # vscode stuff
        - golang.org/x/tools/cmd/gorename         # vscode stuff
        - github.com/tpng/gopkgs                  # vscode stuff
        - github.com/newhook/go-symbols           # vscode stuff
        - golang.org/x/tools/cmd/guru             # vscode stuff
        - github.com/ramya-rao-a/go-outline       # vscode stuff
      args:
        executable: /bin/bash
      tags:
        - golang
        - golang_pkgs

    - name: install some golang packages
      shell: export GOPATH="$HOME/go" && source /etc/profile && go install {{item}}
      with_items:
        - github.com/d4l3k/go-pry                 # debugger/repl
      args:
        executable: /bin/bash
      tags:
        - golang
        - golang_pkgs

    - name: install go linters
      shell: export GOPATH="$HOME/go" && source /etc/profile && gometalinter --install
      args:
        executable: /bin/bash
      ignore_errors: yes
      tags:
        - golang
        - golang_pkgs
