---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: root

  vars_files:
    - ./vars/base.yml

  tasks:

    - name: check if golang is already downloaded
      stat: path=/usr/local/go1.4.2.linux-amd64.tar.gz
      register: golang_file_exist

    - name: download golang
      shell: sudo wget --directory-prefix=/usr/local {{GOLANG_DOWNLOAD_URL}}
      when: golang_file_exist.stat.exists == False

    - name: untar golang file
      command: sudo tar -xzf /usr/local/go1.4.2.linux-amd64.tar.gz chdir=/usr/local/

    - name: golang profileI
      lineinfile: line="\n#golang"
                  backup=yes
                  dest=~/.profile
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: golang profileII
      lineinfile: line="export PATH=$PATH:/usr/local/go/bin"
                  backup=yes
                  dest=~/.profile
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: create golang code dir
      shell: mkdir -p $HOME/mystuff/gocode
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: export golang code dir
      lineinfile: line="export GOPATH=$HOME/mystuff/gocode"
                  backup=yes
                  dest=~/.profile
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: create golang code github dir
      shell: mkdir -p $HOME/mystuff/gocode/src/github.com/komuw
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: golang bashrcI
      lineinfile: line="\n#golang"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: golang bashrcII
      lineinfile: line="export PATH=$PATH:/usr/local/go/bin"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: export golang code dir in bashrc
      lineinfile: line="export GOPATH=$HOME/mystuff/gocode"
                  backup=yes
                  dest=~/.bashrc
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: add $GOPATH to $PATH
      lineinfile: line="export PATH=$HOME/work/gocode/bin:$PATH"
                  backup=yes
                  dest=~/.profile
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"

    - name: source profile
      shell: source ~/.profile
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: source bashrc
      shell: source ~/.bashrc
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: install some golang packages
      shell: export GOPATH="$HOME/mystuff/gocode" && source ~/.profile && go get {{item}}
      with_items:
        - github.com/motemen/gore                 #golang repl
        - github.com/nsf/gocode                   #golang auto-completion
        - github.com/k0kubun/pp                   #pretty print
        - golang.org/x/tools/cmd/godoc            #docs
        - github.com/derekparker/delve/cmd/dlv    #debugger
        - github.com/mailgun/godebug              #another debugger
      tags: go-packages
      sudo: yes
      sudo_user: "{{ansible_ssh_user}}"
      args:
        executable: /bin/bash
