---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: "{{ANSIBLE_SSH_USER}}"

  vars_files:
    - ./vars/base.yml

  tasks:

    - name: download popcorntime io
      get_url: >
        url=https://get.popcorntime.io/build/Popcorn-Time-0.3.8-5-Linux-64.tar.xz
        dest=/tmp

    - name: create popcorntime extract directory
      shell: mkdir -p poptime chdir=/tmp

    - name: untar popcorntime
      shell: sudo tar xf Popcorn-Time-0.3.8-5-Linux-64.tar.xz --directory=poptime chdir=/tmp

    - name: configure custom install popcorntime script(we dont like prompts. do we?)
      template: src=templates/install_popcorntime.sh.j2
                dest=/tmp/poptime/install_popcorntime.sh
      ignore_errors: yes

    - name: install popcorntime
      shell: sudo bash install_popcorntime.sh chdir=/tmp/poptime
      ignore_errors: yes


