---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: "{{ANSIBLE_SSH_USER}}"

  vars_files:
    - ./vars/base.yml

  vars_prompt:

    - name: "ssh_key_passphrase"
      prompt: "Enter private passphrase for pub key"
      private: yes
      default: "{{ DEFAULT_SSH_KEY_PASSPHRASE }}"

  tasks:

    - name: Update package cache if last run was more than 10 hours ago
      apt: update_cache=yes cache_valid_time={{ 60 * 60 * 10 }}

    - name: fix broken dependencies
      shell: sudo apt-get -f -y install

    - name: create /etc/apt/sources.list.d file
      command: mkdir -p /etc/apt/sources.list.d

    - name: rm skype
      shell: sudo apt-get -y remove skype skype-bin:i386 skype:i386
      ignore_errors: yes

    - name: install skype dependency
      shell: sudo apt-get -y install sni-qt:i386

    - name: rm skype config
      shell: sudo rm -rf ~/.Skype

    - name: enable multiarch
      shell: sudo dpkg --add-architecture i386
      ignore_errors: yes

    - name: install gdebi
      shell: sudo apt-get -y update && sudo apt-get -y install gdebi

    - name: add skype ppa
      shell: sudo add-apt-repository -y "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
      ignore_errors: yes

    - name: add some ppas
      shell: sudo add-apt-repository -y {{ item }}
      with_items:
        - "ppa:eugenesan/ppa"
        - "ppa:transmissionbt/ppa"         #transmission bittorrent
        - "ppa:mc3man/trusty-media"     #ffmpeg

      ignore_errors: yes
      register: addppasresult

    - name: install skype
      shell: sudo apt-get -y update && sudo apt-get -y install skype
      ignore_errors: yes

    - name: update cache
      command: sudo apt-get update
      when: addppasresult|success

    - name: remove potential apt lock 
      command: sudo rm -rf /var/cache/apt/archives/lock && sudo rm -rf /var/lib/dpkg/lock && sudo rm /var/cache/debconf/*.dat

    - name: fix broken dependencies
      shell: sudo apt-get -f -y install

    - name: configure
      shell: sudo dpkg --configure -a

    - name: update system
      shell: sudo apt-get -y update

    - name: Install system packages
      shell: sudo apt-get -y install {{ item }}
      with_items:
        - gcc
        - libssl-dev
        - libffi-dev
        - openssh-client
        - openssh-server
        - kdiff3
        - python-pip
        - python3-pip #for docker-compose
        - python-software-properties
        - software-properties-common
        - terminator
        - lsof
        - telnet
        - curl
        - mercurial
        - git
        - unrar
        - transmission
        - libav-tools #needed by vlc for streaming
        - vlc
        - browser-plugin-vlc
        - pep8
        - libpq-dev 
        - python2.7-dev
        - libxml2-dev 
        - libxslt1-dev
        - postgresql 
        - postgresql-contrib
        - network-manager-vpnc
        - vpnc
        - screen
        - build-essential
        - python-dev
        - python-setuptools
        - iftop
        #- ifconfig
        - tcptrack
        - wireshark
        - nano
        - ffmpeg
        - git-flow
        - ffmpeg
        - zip
        - lxc 
        - lxc-templates 
        - cgroup-lite 
        - redir
        - gdb
        - hexchat #irc client
        - mosh
        - vnstat
      ignore_errors: yes

    - name: add nodeJs ppa
      shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

    - name: install nodeJs
      shell: sudo apt-get install -y nodejs

    - name: remove potential apt lock 
      command: sudo rm -rf /var/cache/apt/archives/lock && sudo rm -rf /var/lib/dpkg/lock && sudo rm /var/cache/debconf/*.dat

    - name: fix broken dependencies
      shell: sudo apt-get -f -y install

    - name: configure
      shell: sudo dpkg --configure -a

    - name: update system
      shell: sudo apt-get -y update

    - name: agree to ttf-mscorefonts-installer license(prepare media codecs install)
      shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
      tags: media_codecs

    - name: Install system packages  media codecs
      shell: sudo apt-get -y install ubuntu-restricted-extras
      tags: media_codecs

    - name: update system
      shell: sudo apt-get -y update

    - name: download google chrome 
      get_url: >
        url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
        dest=/tmp

    - name: install google chrome
      command: sudo dpkg -i google-chrome-stable_current_amd64.deb chdir=/tmp
      register: chromeresult
      ignore_errors: yes

    - name: fix install chrome errors
      command: sudo apt-get -f -y install  
      when: chromeresult|failed
      notify:
        - reinstall_chrome

    - name: download sublime-text3 
      get_url: >
        url=http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb 
        dest=/tmp

    - name: install sublime-text3
      command: sudo dpkg -i sublime-text_build-3065_amd64.deb chdir=/tmp
      ignore_errors: yes

    - name: download vagrant 
      get_url: >
        url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1_x86_64.deb 
        dest=/tmp

    - name: install vagrant
      command: sudo dpkg -i vagrant_1.7.1_x86_64.deb chdir=/tmp
      register: checkvagrantresult
      ignore_errors: yes

    - name: install vagrant cachier plugin
      shell: vagrant plugin install vagrant-cachier
      when: checkvagrantresult|success

    - name: download virtualbox
      get_url: >
        url=http://download.virtualbox.org/virtualbox/4.3.30/virtualbox-4.3_4.3.30-101610~Ubuntu~raring_amd64.deb 
        dest=/tmp

    - name: install virtualbox
      command: sudo dpkg -i virtualbox-4.3_4.3.30-101610~Ubuntu~raring_amd64.deb chdir=/tmp
      ignore_errors: yes

    - name: Install Python packages
      shell: sudo pip install --upgrade {{ item }}
      with_items:
        - pip 
        - virtualenv
        - virtualenvwrapper
        - youtube-dl
        - asciinema
        - yapf
        - ansible
        - httpie
        - livestreamer
        - awsebcli
    
    - name: Install Python pip3 packages
      shell: sudo pip3 install --upgrade {{ item }}
      with_items:
        - docker-compose

    - name: create users group
      group: name={{ USER }} state=present

    - name: check if ssh public key exists
      command: cat ~/.ssh/id_rsa.pub
      register: checksshresult
      ignore_errors: yes

    - name: create ssh-key 
      command: ssh-keygen -t rsa -C {{ SSH_KEY_COMMENT }} -b 2048 -q -N {{ ssh_key_passphrase }} -f /home/{{USER}}/.ssh/id_rsa
      when: checksshresult|failed

    #- name: start ssh-agent 
      #shell: ssh-agent /bin/bash

    #- name: load your key to the agent
      #command: ssh-add ~/.ssh/id_rsa

    - name: fetch the new users ssh public key
      shell: cat ~/.ssh/id_rsa.pub
      register: sshkeyresult

    - name: notify user their ssh public key
      debug: var=sshkeyresult

    - name: notify user of location of their ssh public key
      debug: msg="You can always see your public key in $HOME/.ssh/id_rsa.pub"

    - name: configure ssh/config
      template: src=templates/ssh_config.j2 
                dest=~/.ssh/config

    - name: configure bash aliases
      template: src=templates/bash_aliases.j2
                dest=~/.bash_aliases

    - name: configure .bashrc
      template: src=templates/bashrc.j2
                dest=~/.bashrc

    - name: configure .profile
      template: src=templates/profile.j2
                dest=~/.profile

    - name: configure gitconfig
      template: src=templates/gitconfig.j2
                dest=~/.gitconfig

    - name: configure hgrc(mercurial)
      template: src=templates/hgrc.j2
                dest=~/.hgrc

    - name: create pip conf 
      shell: mkdir -p ~/.pip && touch ~/.pip/pip.conf

    - name: configure pip cache conf
      template: src=templates/pip.conf.j2
                dest=~/.pip/pip.conf

    - name: create terminator conf dir
      command: mkdir -p ~/.config/terminator

    - name: configure terminator conf
      template: src=templates/terminator.conf.j2
                dest=~/.config/terminator/config

    - name: clone nvm
      git: >
        repo='https://github.com/creationix/nvm.git'
        dest=~/.nvm
        accept_hostkey=yes 

    - name: source bashrc
      shell: . ~/.bashrc
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: source profile
      shell: . ~/.profile
      ignore_errors: yes
      sudo: no
      ignore_errors: yes
      args:
        executable: /bin/bash

    - name: install nodejs
      command: nvm install {{ NODE_VERSION }}
      ignore_errors: yes

    - name: use that nvm version
      command: nvm use v{{ NODE_VERSION }}
      ignore_errors: yes

    - name: make that node version the default
      command: nvm alias default v{{ NODE_VERSION }}
      ignore_errors: yes

    - name: configure /etc/vpnc/example.conf
      template: src=templates/example.conf.j2
                dest=/etc/vpnc/example.conf
      ignore_errors: yes

    - name: check if docker installed
      command: docker
      register: dockerresult
      ignore_errors: True
      tags: docker
      notify: 
        - finally

    - name: install docker
      shell: sudo wget -qO- https://get.docker.com/ | sh
      when: dockerresult|failed
      tags: docker

    - name: add docker group and add user to it 
      shell: sudo usermod -aG docker {{ANSIBLE_SSH_USER}}
      tags: docker

    - name: Remove some default system packages
      shell: sudo apt-get -y purge {{ item }}
      with_items:
        - netsurf-gtk

    - name: create my stuff dir
      shell: mkdir -p $HOME/mystuff

  handlers:

    - name: reinstall_chrome
      command: sudo dpkg -i google-chrome-stable_current_amd64.deb chdir=/tmp

    - name: finally
      debug: msg="THATS IT. YOU are done."
