
---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: root

  vars_files:
    - ./vars/base.yml

  tasks:
 
    - name: configure pritunl source list
      template: src=templates/pritunl.list.j2
                dest=/etc/apt/sources.list.d/pritunl.list
      tags: 
        - pritunl
 
    - name: add pritunl key
      shell: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A
      tags: 
        - pritunl
  
    - name: update
      shell: sudo apt-get -y update
      tags: 
        - pritunl
 
    - name: install pritunl
      shell: sudo apt-get -y install pritunl-client-gtk
      tags: 
        - pritunl
 
    - name: give dev instructions for steps to follow
      debug:
        msg: "download profile(vpn config)\n start pritunl client from apps\n click import profile (import the config file)\n click connect\n enter 2fa code and u r good to go."
      tags: 
        - pritunl
