# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  provision:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo

    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: provision
          command: |
            bash provision.sh mySShPasshphrase

  editors:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: vscode
          command: |
            bash vscode.sh


  golang:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: golang
          command: |
            bash golang.sh

  dart:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: dart
          command: |
            bash dart.sh

  work:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: work stuff
          command: |
            bash work_stuff.sh

  xonsh:
    docker:
      - image: ubuntu:18.04
    working_directory: /home/komuw/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            bash preRequiste.sh
      - run:
          name: xonsh
          command: |
            bash xonsh.sh

workflows:
  version: 2
  provision-and-everything:
    jobs:
      - provision
      - editors
      - golang
      - dart
      - work
      - xonsh