# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: list directory
          command: |
            pwd; ls -lsha

      -run:
        name: pip version
        command: |
            pip --version

      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                    build-essential \
                                    libssl-dev \
                                    libffi-dev \
                                    python-dev \
                                    software-properties-common \
                                    python-pip
            pip install --ignore-installed -U pip jinja2 paramiko
            apt-get -y update
            apt-get -y install ansible
            pip install -U ansible

      - run:
          name: provision
          command: |
            bash provision.sh mySShPasshphrase

      - run:
          name: editors
          command: |
            bash editors.sh

      - run:
          name: golang
          command: |
            bash golang.sh

      - run:
          name: dart
          command: |
            bash dart.sh

      - run:
          name: daworkrt
          command: |
            bash work_stuff.sh

      - run:
          name: xonsh
          command: |
            bash xonsh.sh
