# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  provision:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: provision
          command: |
            bash provision.sh mySShPasshphrase

  editors:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: editors
          command: |
            bash editors.sh


  golang:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: golang
          command: |
            bash golang.sh

  dart:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: dart
          command: |
            bash dart.sh

  work:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: work stuff
          command: |
            bash work_stuff.sh

  xonsh:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: list directory
          command: |
            pwd; ls -lsha
      - run:
          name: setup
          command: |
            apt-get -y update
            apt-get -y install gcc \
                                build-essential \
                                libssl-dev \
                                libffi-dev \
                                python-dev \
                                software-properties-common \
                                curl \
                                wget
            curl https://bootstrap.pypa.io/get-pip.py | python - 'pip==9.0.3' # see:: https://github.com/pypa/pip/issues/5240
      - run:
          name: xonsh
          command: |
            bash xonsh.sh

workflows:
  version: 2
  provision-and-everything:
    jobs:
      - provision
      - editors
      - golang
      - dart
      - work
      - xonsh