# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: list directory
          command: |
            pwd; ls -lsha

      - run:
          name: setup
          command: |
            bash hardstone.sh mySshKeyPassphrase
