---
ANSIBLE_SSH_USER: komu

DEFAULT_SSH_KEY_PASSPHRASE: "super_secret_pass"

USER: 'komu'
USER_EMAIL: 'myemail@gmail.com'
SSH_KEY_COMMENT: "{{USER_EMAIL}}"

NODE_VERSION: 8.2.1
NODE_ARCHITECTURE: linux-x86


ssh_config:
  - { ip_address: 8.8.8.8, host_name: 'something'}
  - { ip_address: 1.1.1.1, host_name: 'somethingelse'}

GOLANG_VERSION: go1.9.linux-amd64

ATOM_EDITOR_VERSION: "v1.19.5"
