# DOCS: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: hardstone ci
on: [pull_request, push]

jobs:

  preRequiste:
    name: preRequiste
    timeout-minutes: 8
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Check out code into the directory
        uses: actions/checkout@v2

      - name: preRequiste
        run: |
          echo ""
          pwd
          ls -lsha
          echo ""
          echo ""
          /bin/bash linux/preRequiste.sh


  user:
    name: user
    timeout-minutes: 8
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Check out code into the directory
        uses: actions/checkout@v2

      - name: user
        run: |
          /bin/bash linux/user.sh myDummyPassword


  provision:
    name: provision
    timeout-minutes: 8
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Check out code into the directory
        uses: actions/checkout@v2

      - name: provision
        run: |
          /bin/bash linux/provision.sh

